In [1]:
import pystan
import numpy as np

import matplotlib.pyplot as plt

# Regression with normal distribution.

Data Types



* Basic types: real, int, vector, row_vector, matrix
* Constrained types: simplex, unit_vector, ordered, positive_ordered, corr_matrix, cov_matrix

Bounded Variables
* Can put upper and lower bounds on variables
* Ex: real<lower=0> sigma;

Program Blocks
* data (input data we want to fit)
* transformed data (functions of your data)
* parameters (parameters of your model)
* transformed parameters (functions of your parameters)
* model (defines priors of your parameters and "loss" function)
* generated quantities (some additional quantities you want to output)

The only required program block is the model block.

In [2]:
script = """
data {
    int<lower=1> N;
    vector[N] y;
    vector[N] x;
}
parameters {
    real alpha;
    real beta;
    
}
transformed parameters {
  vector[N] mu;

  mu = alpha + x * beta;
}
model {
  // the following defines priors 
  alpha ~ normal(0, 1000);
  beta ~ normal(0, 1000);
  // the following defines "loss"
  y ~ normal(mu, 1);
}
"""


In [3]:
sm = pystan.StanModel(model_code=script) # this may take up to 1 minute

INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_821eaf683878c5e35d7a262b03476e19 NOW.


In [4]:
n_train = 20
x_train = np.random.normal(size=n_train)
y_train = 3*x_train + 1

fit = sm.sampling(data=dict(y=y_train, N=len(y_train), x=x_train))
s = fit.extract()
s

OrderedDict([('alpha',
              array([0.61508944, 0.95163289, 1.00954125, ..., 0.72609786, 0.71219839,
                     1.02309446])),
             ('beta',
              array([2.12775344, 2.23503874, 3.16301888, ..., 2.62063453, 3.08662956,
                     3.39397544])),
             ('mu',
              array([[ 0.67253152,  0.36923411,  2.70192768, ...,  2.50370631,
                       2.05304057, -2.35013129],
                     [ 1.01197131,  0.69338108,  3.14369342, ...,  2.93547735,
                       2.4620882 , -2.16309981],
                     [ 1.09493196,  0.64406421,  4.11173751, ...,  3.81707087,
                       3.14713223, -3.39841739],
                     ...,
                     [ 0.79684604,  0.42329164,  3.29633943, ...,  3.05220129,
                       2.49714158, -2.92599816],
                     [ 0.79552685,  0.35554789,  3.73947424, ...,  3.45192403,
                       2.79816492, -3.58930469],
                     [ 1.

In [5]:
s['mu'].mean(0), y_train

(array([ 1.08521483,  0.6574899 ,  3.94716915, -1.76399451,  1.40875988,
         1.04567583, -1.98804073,  0.46557258, -0.44164262, -0.7919078 ,
         0.66844152,  2.07012121,  2.88185076,  0.21292117, -0.17503042,
         2.23931928,  1.77548164,  3.66762761,  3.03207661, -3.177493  ]),
 array([ 1.08098976,  0.65335928,  3.94231212, -1.76759043,  1.40446337,
         1.04145949, -1.99158718,  0.46148434, -0.44553054, -0.79571837,
         0.66430848,  2.06567866,  2.87722897,  0.20888871, -0.1789772 ,
         2.23483937,  1.77110415,  3.66283231,  3.02742164, -3.1807768 ]))

# Exercise

Modify the previous script so that it has additional parameter on variance. Make a prior to that parameter from exponetial distribution (https://mc-stan.org/docs/2_20/functions-reference/exponential-distribution.html). What parameter sigma did it learn compared to the previous constant value. 

In [6]:
script = """
data {
    int<lower=1> N;
    vector[N] y;
    vector[N] x;
}
parameters {
    real alpha;
    real beta;
    // replace next line with your code
    // <define parameter sigma>
    
}
transformed parameters {
  vector[N] mu;

  mu = alpha + x * beta;
}
model {
  // the following defines priors 
  alpha ~ normal(0, 1000);
  beta ~ normal(0, 1000);
  // <define prior for parameter sigma>
  // <define the loss with sigma>
}
"""

sm = pystan.StanModel(model_code=script) # this may take up to 1 minute

INFO:pystan:COMPILING THE C++ CODE FOR MODEL anon_model_3be6059edddab6ab4e44ab38c965d11e NOW.
